services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tax-calculator-app
    container_name: tax_calculator
    volumes:
      - ./input.txt:/app/input.txt
    command: sh -c "cat input.txt | python src/main.py"